config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('dashboard.urls')),
    path('list/', include('listings.urls')),
    path('faq/', include('faq.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

faq/urls.py
from django.urls import path
from .views import FaqView
from .apps import FaqConfig

app_name = FaqConfig.name

urlpatterns = [
    path('', FaqView.as_view(), name='faq')
]

listings/urls.py
from django.urls import path
from .views import InstitutionView, PlanView, CheckBoxView, AddSuccessView, UpdateListingView
from django.views.decorators.csrf import csrf_exempt
from .apps import ListingsConfig

app_name = ListingsConfig.name
urlpatterns = [
 path('add-institution', InstitutionView.as_view(), name='add_institution'),
 path('update-institution/<str:pk>/', UpdateListingView.as_view(), name='update_institution'),
 path('add-plan', PlanView.as_view(), name='add_plan'),
 path('add-success', AddSuccessView.as_view(), name='add_success'),
 path('checkbox', csrf_exempt(CheckBoxView.as_view()), name='check_box'),
]

listings/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model

User = get_user_model()


def listing_directory_path(instance, filename):
    return f'listing/{instance.list_id}/{filename}'
# Create your models here.
class Listings(models.Model):
    #change id to uuid
        # id = models.UUIDField(primary_key=True, default=uuid4,
        #                   unique=True, editable=False)
    MICROFINANCE_BANK = 'MB'
    COOPERATIVE_SOCIETIES = 'CS'
    FINANCIAL_BANKING = 'FB'
    INSURANCE_COMPANIES = 'IC'


    INSTITUTION_CHOICES = [
        (MICROFINANCE_BANK , 'Microfinance Bank'),
        (COOPERATIVE_SOCIETIES, 'Cooperative Societies'),
        (FINANCIAL_BANKING, 'Financial Banking'),
        (INSURANCE_COMPANIES, 'Insurance Companies')
    ]
    list_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    name = models.CharField(max_length=100)
    institution = models.CharField(max_length=35)
    address = models.CharField(max_length=150)
    description = models.TextField()
    list_image = models.ImageField(upload_to=listing_directory_path, null=True,blank=True)
    start_time = models.TimeField(auto_now=False, auto_now_add=False)
    close_time = models.TimeField(auto_now=False, auto_now_add=False)
    # is_saturday_available = models.BooleanField(default=False)
    # start_time_sat = models.TimeField(auto_now=False, auto_now_add=False)
    # close_time_sat = models.TimeField(auto_now=False, auto_now_add=False)

    @property
    def get_microfinance_count(self):
        return Listings.objects.all().filter(institution='MB').count()
    
    @property
    def get_cooperative_count(self):
        return Listings.objects.all().filter(institution='CS').count()
    
    @property
    def get_financial_count(self):
        return Listings.objects.all().filter(institution='FB').count()

    @property
    def get_insurance_count(self):
        return Listings.objects.all().filter(institution='IC').count()

    # To pass it to the view you can add it to the context in the views.py as count = Feedback.get_feedback_count()
    def __str__(self):
        return self.name
    
    # def get_absolute_url(self):
    #     return reverse("list-detail", kwargs={'pk': str(self.pk)})

    class Meta:
        verbose_name_plural='Listings'
    
class InstitutionCategory(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = 'Institutions Categories'

class Plans(models.Model):
    plan_id = models.ForeignKey(Listings, on_delete=models.CASCADE ,related_name='listings')
    plan_type = models.CharField(max_length=266)
    name = models.CharField(max_length=100)
    plan_image = models.ImageField(upload_to='plans',null=True, blank=True)
    price  = models.FloatField()
    rate = models.CharField(max_length=15)
    percentage_return = models.FloatField()
    max_amount = models.FloatField()
    min_amount = models.FloatField()

    def __str__(self):
        return self.name
        
    class Meta:
        verbose_name_plural='Plans'

class PlanCategory(models.Model):
    # LOAN = 'LN'
    # SAVINGS = 'SS'
    # INVESTMENT = 'IM'
    # PENSION = "PS"
    # INSURANCE = 'IS'
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural='Plans Categories'

listings/forms.py
from django import forms 
from .models import Listings

class ListingsForm(forms.ModelForm):
    class Meta:
        model = Listings

        fields = [
            "name",
            "institution",
            "address",
            "description",
            "start_time",
            "close_time"
        ]

listings/views.py
from django.shortcuts import (render, redirect, get_object_or_404)
from django.views.generic import View
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from .models import Plans, Listings, InstitutionCategory, PlanCategory
import json
from django.http import JsonResponse
from .forms import ListingsForm

# Create your views here.

class SearchListing(View):
    
    def post(self, request):
    # list_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    # name = models.CharField(max_length=100)
    # institution = models.CharField(max_length=2, choices=INSTITUTION_CHOICES)
    # address = models.CharField(max_length=150)
        search_string = json.loads(request.body).get('searchText')
        listing = Listings.objects.filter(
            institution__starts_with=search_string)
        context ={
            'listing': listing
        }
        return render(request, 'dashboard/search-listings', context)
class CheckBoxView(View):
    def post(self, request):
        data = json.loads(request.body)
        check_box = data['checkbox']
        if check_box % 2 == 1:
            return JsonResponse({'check_valid':'Check Box Available'}, status=200)
        return JsonResponse({'check_invalid':True})

class InstitutionView(View):
    def get(self, request):
        listing_instance = Listings.objects.first()
        institution_categories = InstitutionCategory.objects.all()
        context = {
            'listing_instance': listing_instance,
            'institution_categories':institution_categories
        }
        return render(request, 'listings/add-institution.html', context)

    def post(self, request):
        name = request.POST['name']
        description = request.POST['description']
        street = request.POST['street']
        city = request.POST['city']
        state = request.POST['state']
        country = request.POST['country']
        address = f'{street}{city}{state},{country}'
        start_time = request.POST['start_time']
        close_time = request.POST['close_time']
        # sat_work_hours = request.POST['sat_available']
        institution = request.POST['institution']
        image = request.FILES['image']
        #     sat_work_hours = json.loads({'sat':'off'})
        # # data = json.loads(request.body).get('satWok')
        # check_box = data['checkbox']
        # if sat_work_hours ==  'on':
        #     start_time_sat = request.POST['sat_start_time']
        #     close_time_sat = request.POST['sat_close_time']
        Listings.objects.create(list_id=request.user, name=name, description=description, address=address , start_time=start_time, close_time=close_time,institution=institution, list_image=image)
        # start_time = start_time, is_saturday_available = True ,close_time = close_time, start_time_sat = start_time_sat, close_time_sat= close_time_sat,institution=institution,)
        # else:
        #     Listings.objects.create(owner=request.user, name=name, description=description, address=address, 
        # start_time = start_time, is_saturday_available = False ,close_time = close_time, start_time_sat = start_time_sat, close_time_sat= close_time_sat,institution=institution,)

        # listing_instance = Listings.objects.first()
        # context = {
        #     'listing_instance': listing_instance
        # }
    
        return redirect('dashboard')
    
class UpdateListingView(View):
    def get(self, request, pk):
        context = {}

        #fetch the object 
        obj = get_object_or_404(Listings, id=pk)

        form = ListingsForm(request.POST or None, instance = obj)
        if form.is_valid():
            form.save()
            return HttpResponeRedirect("/"+id)
        
        context["form"] = form

        return render(request, "listings/update-listing.html", context)

        


class PlanView(View):
    def get(self, request):
        return render(request, 'listing/add-institution.html')

    def post(self, request):
        plan = request.POST['plan_type']
        plan_name = request.POST['plan_name']
        plan_description = request.POST['plan_description']
        price = request.POST['price']
        rate = request.POST['rate']
        image = request.POST['plan_image']
        return render(request, 'listings/add-institution.html')

class AddSuccessView(View):
    def get(self, request):
        return render(request, 'listings/add-success.html')

templates/listings/add-institution.html
{% extends '_base.html' %}
{% load static %}
{% block content %}
<!-- <aside>
    <p>Step 1</p>
    <p>Step 2</p>
    <p>Step 2</p>
    <p>Step 3</p>
</aside> -->
<link rel="stylesheet" href="{% static 'css/add.css' %}">

<h2>Add Your Institution</h2>
<form action="{% url 'add_institution' %}" class="form1" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
<div>
    <label for="name">Name</label>
    <input type="text" name="name" id="">
</div>
<div>
    <label for="description">Description</label>
    <input type="text" name="description" id="">
</div>
<div>
    <div>
        <label for="street">Street</label>
        <input type="text" name="street" id="">
    </div>
    <div>
        <label for="city">City</label>
        <input type="text" name="city" id="">
    </div>
    <div>
        <label for="state">State</label>
        <input type="text" name="state" id="">
    </div>
    <div>
        <label for="country">Country</label>
        <input type="text" name="country" id="">
    </div>
</div>
<!-- <div>
    <label for="address"> Address </label>
    <input type="text" name="address">
</div> -->
<div>
    <h6>Monday - Friday </h6>
    <label for="start_time">Start Time</label>
    <input type="time" name="start_time" id="">
    <label for="close_time">Close Time</label>
    <input type="time" name="close_time" id="">
</div>

<div>
    <label for="image"></label>
    <input type="file" name="image" id="">
</div>


<!-- <div class="">
    <label for="sat_available">Saturday Availabilty </label>
    <input type="checkbox" name="sat_available" id="satAvailableField">
</div>
<div class="sat_work_hours" style="display: none;">
    <h6>Saturday</h6>
    <label for="sat_start_time">Start Time</label>
    <input type="time" name="sat_start_time" id="">
    <label for="sat_close_time">Close Time</label>
    <input type="time" name="sat_close_time" id="">

</div> -->

<!-- </form> -->

<!-- <form action="" class="form2"> -->
    <!-- <h3>Institution Type    </h3> -->
    <!-- <div class="microfinance__bank">
        <label for="microfinance_bank">Microfinance Bank</label>
        <input type="checkbox" name="microfinance_bank" id="">
    </div>
    <div class="financial__banking">
        <label for="financial__banking">Financial Banking</label>
        <input type="checkbox" name="financial__banking">
    </div>
    <div class="cooperative_societies">
        <label for="cooperative_societies">Cooperative Societies</label>
        <input type="checkbox" name="cooperative__societies" id="">
    </div>
    <div class="Insurance">
        <label for="insurance">Insurance</label>
        <input type="checkbox" name="insurance" id="">
    </div> -->
    <!-- <div>
        <label for="id_institution">Institution Type</label>
        <select name="institution" id="id_institution">
            {% for choice in listing_instance.INSTITUTION_CHOICES %}
            <option value="{{choice.0}}">{{choice.1}}</option>
            {% endfor %}
        </select>
    </div> -->
    <div>
        <label for="institution">Cateogory</label>
        <select name="institution" id="">
            {% for category in institution_categories %}
            <option value="{{ category.name }}">{{category.name}}</option>
            {% endfor %}
        </select>
    </div>
    <button type="submit">Submit</button>
</form>
{% if uploaded_file_url %}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{uploaded_file_url}}</a></p>
{% endif %}
{% block javascript%}
<script src="{% static 'js/add.js' %}"></script>
{% endblock javascript %}
{% endblock content %}

templates/listings/add-plan.html
{% extends '_base.html' %}

{% block content %}
<!-- <aside>
    <p>Step 1</p>
    <p>Step 2</p>
    <p>Step 2</p>
    <p>Step 3</p>
</aside> -->

    <h2>Plans and Pricing</h2>

<form action="" class="form3">
    <div>
        <label for="plan_type">Type of Financial Plan</label>
        <select name="plan_type" id="plan_type">
            <option value="loan">Loan</option>
            <option value="Savings">Insurance</option>
            <option value="Pension">Pension</option>
            <option value="Pension">Pension</option>
        </select>
    </div>
    <div>
        <label for="plan_name">Name</label>
        <input type="text" name="plan_name" id="">
    </div>
    <div>
        <label for="plan_description">Description</label>
        <textarea name="plan_description" placeholder="A description about you planning and Prices">

        </textarea>
    </div>
    <div>
        <label for="price">Price</label>
        <input type="text" name="price" id="">
    </div>

    <div>
        <label for="rate">Rate</label>
        <select name="rate" id="rate">
            <option value="yearly">Yearly</option>
            <option value="monthly">Monthly</option>
            <option value="daily">Daily</option>
        </select>
    </div>
<!-- </form> -->
<small>Add Plan</small>
<!-- <form action="" class="form4"> -->
    <h2>Upload Photos </h2>
    <input type="file" name="plan_image">
    <button type="submit">Submit</button>
</form>

{% endblock content %}

templates/listings/add-success.html
{% extends '_base.html' %}

{% block title %} Success {% endblock title %}

{% block content %}

<a href="{% url 'add_institution' %}"> <button>Add another Listing</button></a>
<a href="{% url 'homepage' %}"><button>Close</button></a>
{% endblock content %}

templates/listings/update-listing.html
{% extends "_base.html" %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <input type="submit" value="Update">
</form>

{% endblock content %}